<script lang="ts">
  import { onMount } from "svelte";
  import mermaid from "mermaid";
  import { GoogleGenerativeAI } from "@google/generative-ai";

  let code = `graph TD
    A[Start] --> B{Is it?}
    B -- Yes --> C[OK]
    C --> D[Rethink]
    D --> B
    B -- No ----> E[End]`;
  let mermaidSvg = "";
  let accessToken = "";
  let isValidToken = false;
  let inputText = "";

  onMount(() => {
    mermaid.initialize({ startOnLoad: true });
    updateMermaid();
  });

  const validateMermaid = async (code: string) => {
    try {
      await mermaid.parse(code);
      return true;
    } catch (error) {
      console.error("Mermaid validation error:", error);
      return false;
    }
  };

  const updateMermaid = async () => {
    if (await validateMermaid(code)) {
      try {
        const { svg } = await mermaid.render("mermaid-graph", code);
        mermaidSvg = svg;
      } catch (error) {
        console.error("Mermaid rendering error:", error);
        mermaidSvg = "Error rendering Mermaid diagram";
      }
    } else {
      mermaidSvg = "Invalid Mermaid syntax";
    }
  };

  const generatePrompt = (inputText: string, code: string) => {
    return `
      You are a Mermaid code generator.
      Please convert the following input into Mermaid code:

      "${inputText}"

      Please ensure the output is a valid Mermaid diagram.

      Current code:
      \`\`\`mermaid
      ${code}
      \`\`\`

      Output only the Mermaid code and nothing else.
    `;
  };

  const analyseResponse = (response: string) => {
    const bracketedContent = response.match(/`mermaid\n([\s\S]+)\n`/);
    if (bracketedContent) {
      response = bracketedContent[1];
    }
    return response;
  };

  const countToken = async () => {
    if (!accessToken) {
      isValidToken = false;
      return;
    }

    try {
      const genAI = new GoogleGenerativeAI(accessToken);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.0-flash-exp",
      });

      const prompt = generatePrompt(inputText, code);
      const result = await model.countTokens(prompt);

      result.totalTokens > 0 ? (isValidToken = true) : (isValidToken = false);

      alert(`Total tokens: ${result.totalTokens}`);
    } catch (error) {
      console.error("Error verifying token:", error);
      isValidToken = false;
    }
  };

  const sendToLLM = async () => {
    if (!accessToken) {
      alert("Please enter access token.");
      return;
    }

    const prompt = generatePrompt(inputText, code);

    try {
      const genAI = new GoogleGenerativeAI(accessToken);
      const model = genAI.getGenerativeModel({
        model: "gemini-1.5-flash",
      });

      const result = await model.generateContent(prompt);

      code = analyseResponse(result.response.text());
      await updateMermaid();
      inputText = "";
    } catch (error) {
      console.error("Error sending to LLM:", error);
    }
  };

  const exportCode = async () => {
    try {
      await navigator.clipboard.writeText(code);
      alert("Mermaid code copied to clipboard!");
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const shareToX = () => {
    const MAX_LENGTH = 250; // ツイートの最大文字数目安（適宜調整）
    let text = "Generated by Mermaid editor:\n`mermaid\n" + code + "\n`";
    if (inputText) {
      text = inputText + "\n" + text;
    }

    // 文字数制限
    if (text.length > MAX_LENGTH) {
      text = text.substring(0, MAX_LENGTH - 3) + "...";
    }

    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
      text
    )}&hashtags=MermaidEditor`;
    window.open(url, "_blank");
  };
</script>

<header class="header">
  <input
    type="password"
    bind:value={accessToken}
    placeholder="Enter access token (hidden)"
    autocomplete="on"
  />
  <button on:click={countToken}>Count Token</button>
  {#if isValidToken}
    <span class="valid-token">Valid Token</span>
  {:else}
    <span class="invalid-token">Invalid Token</span>
  {/if}
  <input
    type="text"
    bind:value={inputText}
    placeholder="Enter text to convert"
  />
  <button on:click={sendToLLM}>Send to LLM</button>
  <button on:click={exportCode}>Export</button>
  <button on:click={shareToX}>Share to X.com</button>
</header>

<main class="content">
  <div class="editor">
    <textarea bind:value={code} on:input={updateMermaid} />
  </div>
  <div class="preview">
    {@html mermaidSvg}
  </div>
</main>

<style>
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px;
    border-bottom: 1px solid #ccc;
  }

  .valid-token {
    color: green;
  }

  .invalid-token {
    color: red;
  }

  .content {
    display: flex;
    height: calc(100vh - 50px); /* Adjust height based on header height */
  }

  .editor {
    width: 50%;
    padding: 10px;
  }

  .editor textarea {
    width: 100%;
    height: 100%;
    resize: none;
    border: 1px solid #ccc;
    font-family: "Courier New", Courier, monospace;
  }

  .preview {
    width: 50%;
    padding: 10px;
    border-left: 1px solid #ccc;
    overflow: auto;
  }
</style>
